
const priorities = { 1: 'Невідкладна', 2: 'Критична', 3: 'Серйозна', 4: 'Звичайна', 5: 'Незначна' };
const actions = { 'insert': 'створено', 'update': 'оновлено' };
const types = { 1: 'Баг', 2: 'Дороботка', 3: 'Завдання', 4: 'Функціональність', 5: 'Техпідтримка' };

const statuses = {
	all: 0,
	active: 0,
	line: 0,
	work: 0,
	review: 0,
	ready: 0,
	rejected: 0,
	suspended: 0,
	review_client: 0
};

const statusesData = [
	{
		id: 0,
		type: 'all',
		title: 'Всі задачі',
		count: 55,
		color: '#2563eb',
		icon: '📋',
		select_item: 0,
		position: 0
	},
	{
		id: 100,
		type: 'active',
		title: 'Активні',
		count: 12,
		color: '#3b82f6',
		icon: '⭕',
		select_item: 0,
		position: 0
	},
	{
		id: 1,
		type: 'line',
		title: 'В черзі',
		count: 10,
		color: '#3182ce',
		icon: '🕒',
		select_item: 1,
		position: 1
	},
	{
		id: 2,
		type: 'work',
		title: 'В роботі',
		count: 1,
		color: '#f59e0b',
		icon: '💼',
		select_item: 1,
		position: 2
	},
	{
		id: 3,
		type: 'review',
		title: 'На перевірці',
		count: 1,
		color: '#805ad5',
		icon: '👁',
		select_item: 1,
		position: 3
	},
	{
		id: 4,
		type: 'ready',
		title: 'Готово',
		count: 31,
		color: '#38a169',
		icon: '✔',
		select_item: 1,
		position: 6
	},
	{
		id: 5,
		type: 'rejected',
		title: 'Відхилено',
		count: 10,
		color: '#e53e3e',
		icon: '✖',
		select_item: 1,
		position: 7
	},
	{
		id: 6,
		type: 'suspended',
		title: 'Призупинено',
		count: 1,
		color: '#537b8f',
		icon: '⏸',
		select_item: 1,
		position: 5
	},
	{
		id: 7,
		type: 'review-client',
		title: 'На перевірці у клієнта',
		count: 1,
		color: '#00BCD4',
		icon: '💬',
		select_item: 1,
		position: 4
	}
];

const tasks = {
	24: {
		"tasks": [
			{
				"id": 103,
				"title": "Анализ - закрытие рейса - ивент сервер",
				"project": "МХП, общие проекты",
				"description": "",
				"source": "",
				"short_source": "",
				"priority": 1,
				"type": 1,
				"status_id": 5,
				"status_name": "Відхилено",
				"status_name_lat": "rejected",
				"responsiblePM": 14,
				"responsiblePMName": "Матицин Андрій",
				"assignedTo": 24,
				"assignedToName": "Клименко Вікторія",
				"createdAt": "2025-08-13",
				"updatedAt": "2025-10-27",
				"planned_execution_date": "2025-08-25",
				"estimate": {
					"hours": 1,
					"minutes": 0
				}
			},
			{
				"id": 177,
				"title": "Відсутнє закриття точки",
				"project": "МХП",
				"description": "",
				"source": "",
				"short_source": "",
				"priority": 1,
				"type": 1,
				"status_id": 5,
				"status_name": "Відхилено",
				"status_name_lat": "rejected",
				"responsiblePM": 14,
				"responsiblePMName": "Матицин Андрій",
				"assignedTo": 24,
				"assignedToName": "Клименко Вікторія",
				"createdAt": "2025-09-18",
				"updatedAt": "2025-10-01",
				"planned_execution_date": "2025-09-18",
				"estimate": {
					"hours": 1,
					"minutes": 0
				}
			},
			{
				"id": 238,
				"title": "Еко Драйвінг",
				"project": "",
				"description": "",
				"source": "",
				"short_source": "",
				"priority": 1,
				"type": 3,
				"status_id": 4,
				"status_name": "Готово",
				"status_name_lat": "ready",
				"responsiblePM": 17,
				"responsiblePMName": "Цимбаліст Оля",
				"assignedTo": 24,
				"assignedToName": "Клименко Вікторія",
				"createdAt": "2025-10-07",
				"updatedAt": "2025-10-27",
				"planned_execution_date": "2025-10-07",
				"estimate": {
					"hours": 1,
					"minutes": 0
				}
			},
			{
				"id": 254,
				"title": "Розрахунок рентабельності",
				"project": "ДельтаМедікал",
				"description": "",
				"source": "",
				"short_source": "",
				"priority": 1,
				"type": 2,
				"status_id": 4,
				"status_name": "Готово",
				"status_name_lat": "ready",
				"responsiblePM": 17,
				"responsiblePMName": "Цимбаліст Оля",
				"assignedTo": 24,
				"assignedToName": "Клименко Вікторія",
				"createdAt": "2025-10-13",
				"updatedAt": "2025-10-16",
				"planned_execution_date": "2025-10-13",
				"estimate": {
					"hours": 1,
					"minutes": 0
				}
			},
			{
				"id": 290,
				"title": "Відключити групування банківських замовлень",
				"project": "Трендіол",
				"description": "",
				"source": "https://business.com/web#id=22736&amp;model=project.task",
				"short_source": "https://business.com/web#id=22736&amp;model...",
				"priority": 1,
				"type": 2,
				"status_id": 4,
				"status_name": "Готово",
				"status_name_lat": "ready",
				"responsiblePM": 22,
				"responsiblePMName": "Панко Павло",
				"assignedTo": 24,
				"assignedToName": "Клименко Вікторія",
				"createdAt": "2025-10-27",
				"updatedAt": "2025-10-30",
				"planned_execution_date": "2025-10-27",
				"estimate": {
					"hours": 1,
					"minutes": 0
				}
			},
			{
				"id": 294,
				"title": "Зберігання та обробка типів товарів",
				"project": "ТЕКС",
				"description": "",
				"source": "https://task.track.com/project/teks-1/us/14?kanban-status=294",
				"short_source": "https://task.track.com/project/teks-1/us/14?kanban-status=294",
				"priority": 1,
				"type": 3,
				"status_id": 4,
				"status_name": "Готово",
				"status_name_lat": "ready",
				"responsiblePM": 17,
				"responsiblePMName": "Цимбаліст Оля",
				"assignedTo": 24,
				"assignedToName": "Клименко Вікторія",
				"createdAt": "2025-10-27",
				"updatedAt": "2025-10-30",
				"planned_execution_date": "2025-10-27",
				"estimate": {
					"hours": 1,
					"minutes": 0
				}
			},
			{
				"id": 367,
				"title": "Проблема с ретрансляцией ПРОД МХП",
				"project": "МХП",
				"description": "",
				"source": "https://yt.innotech.com/issue/MHP-1795",
				"short_source": "https://yt.innotech.com/issue/MHP-1795",
				"priority": 1,
				"type": 1,
				"status_id": 3,
				"status_name": "На перевірці",
				"status_name_lat": "under-review",
				"responsiblePM": 14,
				"responsiblePMName": "Матицин Андрій",
				"assignedTo": 24,
				"assignedToName": "Клименко Вікторія",
				"createdAt": "2025-11-25",
				"updatedAt": "2025-11-27",
				"planned_execution_date": "2025-11-24",
				"estimate": {
					"hours": 1,
					"minutes": 0
				}
			},
			{
				"id": 375,
				"title": "Добавление тегов Магистралка",
				"project": "Магистралка",
				"description": "Добавить теги, изменить согласно значений в документе https://docs.google.com/spreadsheets",
				"source": "",
				"short_source": "",
				"priority": 1,
				"type": 3,
				"status_id": 4,
				"status_name": "Готово",
				"status_name_lat": "ready",
				"responsiblePM": 14,
				"responsiblePMName": "Матицин Андрій",
				"assignedTo": 24,
				"assignedToName": "Клименко Вікторія",
				"createdAt": "2025-11-28",
				"updatedAt": "2025-12-04",
				"planned_execution_date": "2025-11-28",
				"estimate": {
					"hours": 1,
					"minutes": 0
				}
			},
			{
				"id": 276,
				"title": "Зміни у формулі рентабельності",
				"project": "ДельтаМедікал",
				"description": "",
				"source": "",
				"short_source": "",
				"priority": 2,
				"type": 3,
				"status_id": 4,
				"status_name": "Готово",
				"status_name_lat": "ready",
				"responsiblePM": 17,
				"responsiblePMName": "Цимбаліст Оля",
				"assignedTo": 24,
				"assignedToName": "Клименко Вікторія",
				"createdAt": "2025-10-21",
				"updatedAt": "2025-10-24",
				"planned_execution_date": "2025-10-21",
				"estimate": {
					"hours": 1,
					"minutes": 0
				}
			},
			{
				"id": 303,
				"title": "Додавання тегів Магистрлка",
				"project": "Магистралка",
				"description": "",
				"source": "https://yt.innotech.com/issue/MHP-1747",
				"short_source": "https://yt.innotech.com/issue/MHP-1747",
				"priority": 2,
				"type": 4,
				"status_id": 4,
				"status_name": "Готово",
				"status_name_lat": "ready",
				"responsiblePM": 14,
				"responsiblePMName": "Матицин Андрій",
				"assignedTo": 24,
				"assignedToName": "Клименко Вікторія",
				"createdAt": "2025-10-30",
				"updatedAt": "2025-12-04",
				"planned_execution_date": "2025-10-30",
				"estimate": {
					"hours": 1,
					"minutes": 0
				}
			},
			{
				"id": 349,
				"title": "Реалізація нумерації точок маршруту у зворотному порядку з відображенням у стовпці \"КОМЕНТАР\"",
				"project": "ТОВ Рома",
				"description": "",
				"source": "https://task.track.com/project/tov-roma-1/us/3?kanban-status=305",
				"short_source": "https://task.track.com/project/tov-roma-1/us/3?kanban-status=305",
				"priority": 2,
				"type": 2,
				"status_id": 4,
				"status_name": "Готово",
				"status_name_lat": "ready",
				"responsiblePM": 17,
				"responsiblePMName": "Цимбаліст Оля",
				"assignedTo": 24,
				"assignedToName": "Клименко Вікторія",
				"createdAt": "2025-11-18",
				"updatedAt": "2025-12-02",
				"planned_execution_date": "2025-11-18",
				"estimate": {
					"hours": 1,
					"minutes": 0
				}
			},
			{
				"id": 134,
				"title": "Добавление Тегов Баку",
				"project": "Юмико",
				"description": "",
				"source": "",
				"short_source": "",
				"priority": 3,
				"type": 2,
				"status_id": 4,
				"status_name": "Готово",
				"status_name_lat": "ready",
				"responsiblePM": 22,
				"responsiblePMName": "Панко Павло",
				"assignedTo": 24,
				"assignedToName": "Клименко Вікторія",
				"createdAt": "2025-08-21",
				"updatedAt": "2025-10-27",
				"planned_execution_date": "2025-08-21",
				"estimate": {
					"hours": 1,
					"minutes": 0
				}
			},
			{
				"id": 200,
				"title": "Кросс - докинг",
				"project": "Машистралка",
				"description": "",
				"source": "",
				"short_source": "",
				"priority": 3,
				"type": 4,
				"status_id": 5,
				"status_name": "Відхилено",
				"status_name_lat": "rejected",
				"responsiblePM": 21,
				"responsiblePMName": "Деркач Андрій",
				"assignedTo": 24,
				"assignedToName": "Клименко Вікторія",
				"createdAt": "2025-09-25",
				"updatedAt": "2025-11-24",
				"planned_execution_date": "2025-09-25",
				"estimate": {
					"hours": 1,
					"minutes": 0
				}
			},
			{
				"id": 213,
				"title": "Проблема с групировкой в HESH рейсах на перемещение",
				"project": "Юміко",
				"description": "",
				"source": "https://business.com/web#id=21749&amp;action=158&amp;active_id=640&amp;model=project.task&amp;view_type=form&amp;cids=1&amp;menu_id=102",
				"short_source": "https://business.com/web#id=21749&amp;action=158&amp;active_id=640&amp;model...",
				"priority": 3,
				"type": 1,
				"status_id": 5,
				"status_name": "Відхилено",
				"status_name_lat": "rejected",
				"responsiblePM": 22,
				"responsiblePMName": "Панко Павло",
				"assignedTo": 24,
				"assignedToName": "Клименко Вікторія",
				"createdAt": "2025-09-30",
				"updatedAt": "2025-11-24",
				"planned_execution_date": "2025-09-30",
				"estimate": {
					"hours": 1,
					"minutes": 0
				}
			},
			{
				"id": 397,
				"title": "Убрать FORAUTO и склад финиша в конце рейса, в последнем маршруте курьера добавлять дом",
				"project": "Заказ.юа",
				"description": "",
				"source": "https://task.track.com/project/zakazua/us/15?kanban-include_attachments=1&amp;kanban-include_tasks=1&amp;kanban-status=117",
				"short_source": "https://task.track.com/project/zakazua/us/15?kanban-include_attachments=1&amp;ka...",
				"priority": 3,
				"type": 2,
				"status_id": 1,
				"status_name": "В черзі",
				"status_name_lat": "active",
				"responsiblePM": 19,
				"responsiblePMName": "Костоправова Аня",
				"assignedTo": 24,
				"assignedToName": "Клименко Вікторія",
				"createdAt": "2025-12-03",
				"updatedAt": "2025-12-03",
				"planned_execution_date": "2025-12-03",
				"estimate": {
					"hours": 1,
					"minutes": 0
				}
			},
			{
				"id": 195,
				"title": "Ковальская - изменение логики закрытия точек",
				"project": "Ковальская",
				"description": "",
				"source": "",
				"short_source": "",
				"priority": 4,
				"type": 4,
				"status_id": 1,
				"status_name": "В черзі",
				"status_name_lat": "active",
				"responsiblePM": 14,
				"responsiblePMName": "Матицин Андрій",
				"assignedTo": 24,
				"assignedToName": "Клименко Вікторія",
				"createdAt": "2025-09-23",
				"updatedAt": "2025-10-27",
				"planned_execution_date": "2025-09-23",
				"estimate": {
					"hours": 1,
					"minutes": 0
				}
			},
			{
				"id": 260,
				"title": "Проблема при створенні коробів",
				"project": "Юміко",
				"description": "",
				"source": "https://business.com/web#id=22709&amp;amp;action=158&amp;amp;active_id=648&amp;amp;model=project.task&amp;amp;view_type=form&amp;amp;cids=&amp;amp;menu_id=102",
				"short_source": "https://business.com/web#id=22709&amp;amp;action=158&amp;amp;active_id=648&a...",
				"priority": 4,
				"type": 1,
				"status_id": 5,
				"status_name": "Відхилено",
				"status_name_lat": "rejected",
				"responsiblePM": 22,
				"responsiblePMName": "Панко Павло",
				"assignedTo": 24,
				"assignedToName": "Клименко Вікторія",
				"createdAt": "2025-10-15",
				"updatedAt": "2025-11-03",
				"planned_execution_date": "2025-10-15",
				"estimate": {
					"hours": 1,
					"minutes": 0
				}
			},
			{
				"id": 354,
				"title": "Сторінка трекінга. Неправельний час",
				"project": "Трендіол",
				"description": "Баг1! https://business.com/web#action=483&amp;active_id=6&amp;cids=1&amp;id=23045&amp;menu_id=102&amp;model=project.task&amp;view_type=form \r\nБаг2! https://business.com/web#action=483&amp;active_id=6&amp;cids=1&amp;id=23046&amp;menu_id=102&amp;model=project.task&amp;view_type=form",
				"source": "",
				"short_source": "",
				"priority": 4,
				"type": 1,
				"status_id": 3,
				"status_name": "На перевірці",
				"status_name_lat": "under-review",
				"responsiblePM": 22,
				"responsiblePMName": "Панко Павло",
				"assignedTo": 24,
				"assignedToName": "Клименко Вікторія",
				"createdAt": "2025-11-20",
				"updatedAt": "2025-11-30",
				"planned_execution_date": "2025-11-20",
				"estimate": {
					"hours": 1,
					"minutes": 0
				}
			}
		],
		"statuses": {
			"all": 18,
			"active": "4",
			"line": "2",
			"work": "0",
			"review": "2",
			"ready": "9",
			"rejected": "5",
			"suspended": "0",
			"review_client": "0"
		}
	},
	6: {
		"tasks": [
			{
				"id": 629,
				"title": "Налаштування мобільного - не знімати геокоординати",
				"project": "Магистралка",
				"description": "",
				"source": "",
				"short_source": "",
				"priority": 3,
				"type": 4,
				"status_id": 2,
				"status_name": "В роботі",
				"status_name_lat": "in-progress",
				"responsiblePM": 14,
				"responsiblePMName": "Матицин Андрій",
				"assignedTo": 6,
				"assignedToName": "Тесленко Олександр",
				"createdAt": "2026-07-10",
				"updatedAt": "2026-07-10",
				"planned_execution_date": "2026-07-10",
				"estimate": {
					"hours": 1,
					"minutes": 0
				}
			},
			{
				"id": 512,
				"title": "Перевірити маркери на карті",
				"project": "Юнікс",
				"description": "",
				"source": "https://task.track.com/project/iunik-treid/issue/27",
				"short_source": "https://task.track.com/project/iunik-treid/issue/27",
				"priority": 4,
				"type": 1,
				"status_id": 2,
				"status_name": "В роботі",
				"status_name_lat": "in-progress",
				"responsiblePM": 19,
				"responsiblePMName": "Костоправова Аня",
				"assignedTo": 6,
				"assignedToName": "Тесленко Олександр",
				"createdAt": "2026-05-22",
				"updatedAt": "2026-07-14",
				"planned_execution_date": "2026-05-22",
				"estimate": {
					"hours": 1,
					"minutes": 0
				}
			},
			{
				"id": 407,
				"title": "Додати параметр врахувати ВІП для с10, 474 інстансу",
				"project": "МХП Одеса",
				"description": "",
				"source": "https://task.track.com/project/tms/us/30?kanban-status=164",
				"short_source": "https://task.track.com/project/tms/us/30?kanban-status=164",
				"priority": 1,
				"type": 3,
				"status_id": 3,
				"status_name": "На перевірці",
				"status_name_lat": "under-review",
				"responsiblePM": 17,
				"responsiblePMName": "Цимбаліст Оля",
				"assignedTo": 6,
				"assignedToName": "Тесленко Олександр",
				"createdAt": "2025-12-04",
				"updatedAt": "2025-12-04",
				"planned_execution_date": "2025-12-04",
				"estimate": {
					"hours": 1,
					"minutes": 0
				}
			},
			{
				"id": 371,
				"title": "Метод иморта авто",
				"project": "Магистралка",
				"description": "",
				"source": "https://yt.innotech.com/issue/MHP-1799",
				"short_source": "https://yt.innotech.com/issue/MHP-1799",
				"priority": 2,
				"type": 4,
				"status_id": 3,
				"status_name": "На перевірці",
				"status_name_lat": "under-review",
				"responsiblePM": 14,
				"responsiblePMName": "Матицин Андрій",
				"assignedTo": 6,
				"assignedToName": "Тесленко Олександр",
				"createdAt": "2025-11-27",
				"updatedAt": "2025-11-28",
				"planned_execution_date": "2025-11-27",
				"estimate": {
					"hours": 1,
					"minutes": 0
				}
			},
			{
				"id": 315,
				"title": "Самовывоз - проверка смс",
				"project": "Магистралка",
				"description": "",
				"source": "https://85.151.47.24/oauth?state=%2Fissue%2FMHP-1749",
				"short_source": "https://85.151.47.24/oauth?state=%2Fissue%2FMHP-1749",
				"priority": 3,
				"type": 1,
				"status_id": 3,
				"status_name": "На перевірці",
				"status_name_lat": "under-review",
				"responsiblePM": 14,
				"responsiblePMName": "Матицин Андрій",
				"assignedTo": 6,
				"assignedToName": "Тесленко Олександр",
				"createdAt": "2025-11-03",
				"updatedAt": "2025-11-05",
				"planned_execution_date": "2025-11-03",
				"estimate": {
					"hours": 1,
					"minutes": 0
				}
			},
			{
				"id": 329,
				"title": "Киоск - выбор авто",
				"project": "Магистралка",
				"description": "FindCar2\r\n\r\n/api/find/car",
				"source": "",
				"short_source": "",
				"priority": 3,
				"type": 4,
				"status_id": 3,
				"status_name": "На перевірці",
				"status_name_lat": "under-review",
				"responsiblePM": 14,
				"responsiblePMName": "Матицин Андрій",
				"assignedTo": 6,
				"assignedToName": "Тесленко Олександр",
				"createdAt": "2025-11-07",
				"updatedAt": "2025-11-07",
				"planned_execution_date": "2025-11-07",
				"estimate": {
					"hours": 1,
					"minutes": 0
				}
			},
			{
				"id": 396,
				"title": "Киоск - вывод товаров",
				"project": "ФЕМ",
				"description": "",
				"source": "",
				"short_source": "",
				"priority": 3,
				"type": 3,
				"status_id": 6,
				"status_name": "Призупинено",
				"status_name_lat": "suspended",
				"responsiblePM": 14,
				"responsiblePMName": "Матицин Андрій",
				"assignedTo": 6,
				"assignedToName": "Тесленко Олександр",
				"createdAt": "2025-12-03",
				"updatedAt": "2026-06-09",
				"planned_execution_date": "2025-12-03",
				"estimate": {
					"hours": 1,
					"minutes": 0
				}
			},
			{
				"id": 405,
				"title": "Налаштування с21",
				"project": "Коноваленко",
				"description": "",
				"source": "",
				"short_source": "",
				"priority": 3,
				"type": 1,
				"status_id": 1,
				"status_name": "В черзі",
				"status_name_lat": "active",
				"responsiblePM": 14,
				"responsiblePMName": "Матицин Андрій",
				"assignedTo": 6,
				"assignedToName": "Тесленко Олександр",
				"createdAt": "2025-12-04",
				"updatedAt": "2025-12-04",
				"planned_execution_date": "2025-12-04",
				"estimate": {
					"hours": 1,
					"minutes": 0
				}
			},
			{
				"id": 406,
				"title": "Перенос ТМС/ЯРД/Митинг",
				"project": "Общий проект",
				"description": "",
				"source": "",
				"short_source": "",
				"priority": 3,
				"type": 1,
				"status_id": 1,
				"status_name": "В черзі",
				"status_name_lat": "active",
				"responsiblePM": 14,
				"responsiblePMName": "Матицин Андрій",
				"assignedTo": 6,
				"assignedToName": "Тесленко Олександр",
				"createdAt": "2025-12-04",
				"updatedAt": "2025-12-04",
				"planned_execution_date": "2025-12-04",
				"estimate": {
					"hours": 1,
					"minutes": 0
				}
			},
			{
				"id": 385,
				"title": "Киоск - Поиск заявки",
				"project": "ФЕМ",
				"description": "",
				"source": "",
				"short_source": "",
				"priority": 4,
				"type": 4,
				"status_id": 1,
				"status_name": "В черзі",
				"status_name_lat": "active",
				"responsiblePM": 14,
				"responsiblePMName": "Матицин Андрій",
				"assignedTo": 6,
				"assignedToName": "Тесленко Олександр",
				"createdAt": "2025-12-02",
				"updatedAt": "2025-12-02",
				"planned_execution_date": "2025-12-02",
				"estimate": {
					"hours": 1,
					"minutes": 0
				}
			},
			{
				"id": 398,
				"title": "Синхронизация водителя между авто планирования и обьекта",
				"project": "Сузирья",
				"description": "",
				"source": "https://task.track.com/project/suziria/us/78?kanban-include_attachments=1&amp;kanban-include_tasks=1&amp;kanban-status=91",
				"short_source": "https://task.track.com/project/suziria/us/78?kanban-include_attachments=1&amp;ka...",
				"priority": 4,
				"type": 2,
				"status_id": 1,
				"status_name": "В черзі",
				"status_name_lat": "active",
				"responsiblePM": 19,
				"responsiblePMName": "Костоправова Аня",
				"assignedTo": 6,
				"assignedToName": "Тесленко Олександр",
				"createdAt": "2025-12-03",
				"updatedAt": "2025-12-03",
				"planned_execution_date": "2025-12-03",
				"estimate": {
					"hours": 1,
					"minutes": 0
				}
			},
			{
				"id": 403,
				"title": "Почистить тестовые проекты",
				"project": "Общее",
				"description": "С6, ПТД, 478 інстанс \r\nс5, Бусмаркет, 436 інстанс\r\nс8, ТОВ Рома, 211 інстанс\r\nc11, ЛПК, 87 інстанс\r\nс6, ПТД, 478 інстанс \r\nс5, Бусмаркет, 436 інстанс\r\nс8, ТОВ Рома, 211 інстанс\r\nc11, ЛПК, 87 інстанс\r\nс3, Хортиця, 328 інстанс\r\nс5, Культтовары, 307 инстанс\r\nс8, Баядера, 419 инстанс\r\nс12, Заказ.юа, 346 инстанс\r\nс19 Сузирья, 453 инстанс\r\nс22, Юрия Фарм, 321 инстанс\r\nЮникс, тмс.утр, \r\nКТ-Днипро",
				"source": "",
				"short_source": "",
				"priority": 5,
				"type": 5,
				"status_id": 1,
				"status_name": "В черзі",
				"status_name_lat": "active",
				"responsiblePM": 19,
				"responsiblePMName": "Костоправова Аня",
				"assignedTo": 6,
				"assignedToName": "Тесленко Олександр",
				"createdAt": "2025-12-03",
				"updatedAt": "2025-12-03",
				"planned_execution_date": "2025-12-03",
				"estimate": {
					"hours": 1,
					"minutes": 0
				}
			},
			{
				"id": 138,
				"title": "Розгортання та налаштування нового порталу ДТЕК",
				"project": "ДТЕК",
				"description": "",
				"source": "",
				"short_source": "",
				"priority": 1,
				"type": 4,
				"status_id": 4,
				"status_name": "Готово",
				"status_name_lat": "ready",
				"responsiblePM": 18,
				"responsiblePMName": "Пашкова Вікторія",
				"assignedTo": 6,
				"assignedToName": "Тесленко Олександр",
				"createdAt": "2025-08-26",
				"updatedAt": "2025-09-30",
				"planned_execution_date": "2025-09-09",
				"estimate": {
					"hours": 1,
					"minutes": 0
				}
			},
			{
				"id": 152,
				"title": "Дополнительная проверка при отмене рейса",
				"project": "Ковальская",
				"description": "",
				"source": "https://yt.innotech.com/issue/TMSKOVALSKA-286",
				"short_source": "https://yt.innotech.com/issue/TMSKOVALSKA-286",
				"priority": 1,
				"type": 1,
				"status_id": 4,
				"status_name": "Готово",
				"status_name_lat": "ready",
				"responsiblePM": 14,
				"responsiblePMName": "Матицин Андрій",
				"assignedTo": 6,
				"assignedToName": "Тесленко Олександр",
				"createdAt": "2025-09-09",
				"updatedAt": "2025-09-30",
				"planned_execution_date": "2025-09-09",
				"estimate": {
					"hours": 1,
					"minutes": 0
				}
			},
			{
				"id": 167,
				"title": "Укрпошта - розподіл заявок по проектах",
				"project": "Укрпошта",
				"description": "",
				"source": "https://yt.innotech.com/issue/ukrpost1-553",
				"short_source": "https://yt.innotech.com/issue/ukrpost1-553",
				"priority": 1,
				"type": 2,
				"status_id": 4,
				"status_name": "Готово",
				"status_name_lat": "ready",
				"responsiblePM": 17,
				"responsiblePMName": "Цимбаліст Оля",
				"assignedTo": 6,
				"assignedToName": "Тесленко Олександр",
				"createdAt": "2025-09-15",
				"updatedAt": "2025-09-16",
				"planned_execution_date": "2025-09-15",
				"estimate": {
					"hours": 1,
					"minutes": 0
				}
			},
			{
				"id": 206,
				"title": "Налаштування списку комісій за кодом ТМЦ",
				"project": "ДТЕК",
				"description": "Зробити привʼязку відповідальних за приймання по кодам ТМЦ з можливістю редагувати комісію вручну,  ТЗ нижче за посиланням  \r\nhttps://docs.google.com/document",
				"source": "https://85.151.47.24/issue/12342122-176",
				"short_source": "https://85.151.47.24/issue/12342122-176",
				"priority": 1,
				"type": 2,
				"status_id": 4,
				"status_name": "Готово",
				"status_name_lat": "ready",
				"responsiblePM": 18,
				"responsiblePMName": "Пашкова Вікторія",
				"assignedTo": 6,
				"assignedToName": "Тесленко Олександр",
				"createdAt": "2025-09-29",
				"updatedAt": "2025-11-03",
				"planned_execution_date": "2025-09-29",
				"estimate": {
					"hours": 1,
					"minutes": 0
				}
			},
			{
				"id": 218,
				"title": "ДельтаМедікал - Ограничение распределения заявок из геозоны в разные рейсы",
				"project": "ДельтаМедікал",
				"description": "В XML-пакете `AutoplanTrip` нужно добавить новый атрибут:\r\n\r\nНазвание атрибута: `UseZoneToVehicleConstraints`      \r\nТип: boolean (0/1, true/false)      \r\nЗначение по умолчанию: 0 (false)",
				"source": "https://task.track.com/project/tms/us/17",
				"short_source": "https://task.track.com/project/tms/us/17",
				"priority": 1,
				"type": 2,
				"status_id": 4,
				"status_name": "Готово",
				"status_name_lat": "ready",
				"responsiblePM": 17,
				"responsiblePMName": "Цимбаліст Оля",
				"assignedTo": 6,
				"assignedToName": "Тесленко Олександр",
				"createdAt": "2025-10-02",
				"updatedAt": "2025-10-07",
				"planned_execution_date": "2025-10-02",
				"estimate": {
					"hours": 1,
					"minutes": 0
				}
			},
			{
				"id": 248,
				"title": "Довідник \"Об'єкти\"",
				"project": "Zammler ML",
				"description": "Додати інформаційні поля в \"об'єкти\"",
				"source": "https://yt.innotech.com/issue/MHP-1715",
				"short_source": "https://yt.innotech.com/issue/MHP-1715",
				"priority": 1,
				"type": 2,
				"status_id": 4,
				"status_name": "Готово",
				"status_name_lat": "ready",
				"responsiblePM": 21,
				"responsiblePMName": "Деркач Андрій",
				"assignedTo": 6,
				"assignedToName": "Тесленко Олександр",
				"createdAt": "2025-10-13",
				"updatedAt": "2025-11-03",
				"planned_execution_date": "2025-10-13",
				"estimate": {
					"hours": 8,
					"minutes": 0
				}
			},
			{
				"id": 249,
				"title": "Довідник \"Водії\"",
				"project": "Zammler ML",
				"description": "Збереження скану супутніх документів водія",
				"source": "https://yt.innotech.com/issue/MHP-1716",
				"short_source": "https://yt.innotech.com/issue/MHP-1716",
				"priority": 1,
				"type": 2,
				"status_id": 4,
				"status_name": "Готово",
				"status_name_lat": "ready",
				"responsiblePM": 21,
				"responsiblePMName": "Деркач Андрій",
				"assignedTo": 6,
				"assignedToName": "Тесленко Олександр",
				"createdAt": "2025-10-13",
				"updatedAt": "2025-11-03",
				"planned_execution_date": "2025-10-13",
				"estimate": {
					"hours": 3,
					"minutes": 0
				}
			},
			{
				"id": 253,
				"title": "Додати можливість клієнту самостійно задавати час пошуку рішення для автоплану",
				"project": "Дельта Медікал",
				"description": "",
				"source": "https://task.track.com/project/tms/us/20?kanban-status=164",
				"short_source": "https://task.track.com/project/tms/us/20?kanban-status=164",
				"priority": 1,
				"type": 2,
				"status_id": 4,
				"status_name": "Готово",
				"status_name_lat": "ready",
				"responsiblePM": 17,
				"responsiblePMName": "Цимбаліст Оля",
				"assignedTo": 6,
				"assignedToName": "Тесленко Олександр",
				"createdAt": "2025-10-13",
				"updatedAt": "2025-10-16",
				"planned_execution_date": "2025-10-13",
				"estimate": {
					"hours": 1,
					"minutes": 0
				}
			},
			{
				"id": 310,
				"title": "Оптимізація привʼязки в рейсі",
				"project": "ДТЕК",
				"description": "Налаштування привʼязки склад - завод + відображення заявок шипментів певної станції окремо",
				"source": "https://85.151.47.24/issue/12342122-180",
				"short_source": "https://85.151.47.24/issue/12342122-180",
				"priority": 1,
				"type": 2,
				"status_id": 4,
				"status_name": "Готово",
				"status_name_lat": "ready",
				"responsiblePM": 18,
				"responsiblePMName": "Пашкова Вікторія",
				"assignedTo": 6,
				"assignedToName": "Тесленко Олександр",
				"createdAt": "2025-11-03",
				"updatedAt": "2025-11-07",
				"planned_execution_date": "2025-11-03",
				"estimate": {
					"hours": 5,
					"minutes": 0
				}
			},
			{
				"id": 343,
				"title": "Баг з розподілом ТМЦ",
				"project": "ДТЕК",
				"description": "",
				"source": "",
				"short_source": "",
				"priority": 1,
				"type": 1,
				"status_id": 4,
				"status_name": "Готово",
				"status_name_lat": "ready",
				"responsiblePM": 18,
				"responsiblePMName": "Пашкова Вікторія",
				"assignedTo": 6,
				"assignedToName": "Тесленко Олександр",
				"createdAt": "2025-11-13",
				"updatedAt": "2025-11-18",
				"planned_execution_date": "2025-11-14",
				"estimate": {
					"hours": 1,
					"minutes": 0
				}
			},
			{
				"id": 350,
				"title": "Додати нове налаштування «Статус планування» у довіднику «Об'єкти»",
				"project": "Еліт",
				"description": "",
				"source": "https://task.track.com/project/elit-ukraine/us/2?kanban-status=358",
				"short_source": "https://task.track.com/project/elit-ukraine/us/2?kanban-status=358",
				"priority": 1,
				"type": 3,
				"status_id": 4,
				"status_name": "Готово",
				"status_name_lat": "ready",
				"responsiblePM": 17,
				"responsiblePMName": "Цимбаліст Оля",
				"assignedTo": 6,
				"assignedToName": "Тесленко Олександр",
				"createdAt": "2025-11-18",
				"updatedAt": "2025-12-03",
				"planned_execution_date": "2025-11-18",
				"estimate": {
					"hours": 1,
					"minutes": 0
				}
			},
			{
				"id": 401,
				"title": "Додати інстанс для нового клієнта на сервері с10, назва клієнта - ПриватБанк",
				"project": "Приватбанк",
				"description": "",
				"source": "",
				"short_source": "",
				"priority": 1,
				"type": 3,
				"status_id": 4,
				"status_name": "Готово",
				"status_name_lat": "ready",
				"responsiblePM": 17,
				"responsiblePMName": "Цимбаліст Оля",
				"assignedTo": 6,
				"assignedToName": "Тесленко Олександр",
				"createdAt": "2025-12-03",
				"updatedAt": "2025-12-03",
				"planned_execution_date": "2025-12-03",
				"estimate": {
					"hours": 1,
					"minutes": 0
				}
			},
			{
				"id": 106,
				"title": "Бусмаркет - додавання параметру Максимальний час доїзду до останньї точки в автоплан",
				"project": "Бусмаркет",
				"description": "",
				"source": "https://task.track.com/project/busmarket/us/22?kanban-status=104",
				"short_source": "https://task.track.com/project/busmarket/us/22?kanban-status=104",
				"priority": 2,
				"type": 1,
				"status_id": 4,
				"status_name": "Готово",
				"status_name_lat": "ready",
				"responsiblePM": 17,
				"responsiblePMName": "Цимбаліст Оля",
				"assignedTo": 6,
				"assignedToName": "Тесленко Олександр",
				"createdAt": "2025-08-13",
				"updatedAt": "2025-08-13",
				"planned_execution_date": "2025-08-13",
				"estimate": {
					"hours": 1,
					"minutes": 0
				}
			},
			{
				"id": 107,
				"title": "Оновлення ДТЕК - центральна база",
				"project": "ДТЕК",
				"description": "",
				"source": "",
				"short_source": "",
				"priority": 2,
				"type": 5,
				"status_id": 4,
				"status_name": "Готово",
				"status_name_lat": "ready",
				"responsiblePM": 18,
				"responsiblePMName": "Пашкова Вікторія",
				"assignedTo": 6,
				"assignedToName": "Тесленко Олександр",
				"createdAt": "2025-08-13",
				"updatedAt": "2025-08-14",
				"planned_execution_date": "2025-08-13",
				"estimate": {
					"hours": 0,
					"minutes": 0
				}
			},
			{
				"id": 148,
				"title": "ДТЕК генерація для станцій",
				"project": "ДТЕК",
				"description": "Привʼязка користувачів за кодом заводу",
				"source": "https://85.151.47.24/issue/12342122-175",
				"short_source": "https://85.151.47.24/issue/12342122-175",
				"priority": 2,
				"type": 2,
				"status_id": 4,
				"status_name": "Готово",
				"status_name_lat": "ready",
				"responsiblePM": 18,
				"responsiblePMName": "Пашкова Вікторія",
				"assignedTo": 6,
				"assignedToName": "Тесленко Олександр",
				"createdAt": "2025-09-05",
				"updatedAt": "2025-10-14",
				"planned_execution_date": "2025-09-05",
				"estimate": {
					"hours": 1,
					"minutes": 0
				}
			},
			{
				"id": 207,
				"title": "Перевірити : при даблік на точку рейса не цетрується карта ОСМ",
				"project": "Сузирья",
				"description": "",
				"source": "https://task.track.com/project/suziria/us/73?kanban-include_attachments=1&amp;amp;amp;kanban-include_tasks=1&amp;amp;amp;kanban-status=91",
				"short_source": "https://task.track.com/project/suziria/us/73?kanban-include_attachments=1&amp;am...",
				"priority": 2,
				"type": 5,
				"status_id": 4,
				"status_name": "Готово",
				"status_name_lat": "ready",
				"responsiblePM": 19,
				"responsiblePMName": "Костоправова Аня",
				"assignedTo": 6,
				"assignedToName": "Тесленко Олександр",
				"createdAt": "2025-09-29",
				"updatedAt": "2025-10-13",
				"planned_execution_date": "2025-09-29",
				"estimate": {
					"hours": 1,
					"minutes": 0
				}
			},
			{
				"id": 242,
				"title": "Зауваження - Моб АПИ",
				"project": "Магистралка",
				"description": "380610510033 - нет смены, хотя она есть)\r\n380610510035 - при постановке в смену - ставит на 1 филиал код, должен біть 12082025",
				"source": "",
				"short_source": "",
				"priority": 2,
				"type": 1,
				"status_id": 4,
				"status_name": "Готово",
				"status_name_lat": "ready",
				"responsiblePM": 14,
				"responsiblePMName": "Матицин Андрій",
				"assignedTo": 6,
				"assignedToName": "Тесленко Олександр",
				"createdAt": "2025-10-09",
				"updatedAt": "2025-10-14",
				"planned_execution_date": "2025-10-08",
				"estimate": {
					"hours": 1,
					"minutes": 0
				}
			},
			{
				"id": 270,
				"title": "Еко Драйвінг",
				"project": "Еліт",
				"description": "Https://task.track.com/project/tms/us/24?kanban-status=164",
				"source": "https://task.track.com/project/tms/us/22?kanban-status=163",
				"short_source": "https://task.track.com/project/tms/us/22?kanban-status=163",
				"priority": 2,
				"type": 2,
				"status_id": 4,
				"status_name": "Готово",
				"status_name_lat": "ready",
				"responsiblePM": 17,
				"responsiblePMName": "Цимбаліст Оля",
				"assignedTo": 6,
				"assignedToName": "Тесленко Олександр",
				"createdAt": "2025-10-16",
				"updatedAt": "2025-10-27",
				"planned_execution_date": "2025-10-31",
				"estimate": {
					"hours": 1,
					"minutes": 0
				}
			},
			{
				"id": 297,
				"title": "ЕкоДрайвінг - зауваження, доопрацювання",
				"project": "Еліт",
				"description": "",
				"source": "https://task.track.com/project/tms/us/25?kanban-status=164",
				"short_source": "https://task.track.com/project/tms/us/25?kanban-status=164",
				"priority": 2,
				"type": 2,
				"status_id": 4,
				"status_name": "Готово",
				"status_name_lat": "ready",
				"responsiblePM": 17,
				"responsiblePMName": "Цимбаліст Оля",
				"assignedTo": 6,
				"assignedToName": "Тесленко Олександр",
				"createdAt": "2025-10-28",
				"updatedAt": "2025-10-29",
				"planned_execution_date": "2025-10-28",
				"estimate": {
					"hours": 1,
					"minutes": 0
				}
			},
			{
				"id": 104,
				"title": "МХП - моб АПИ - дополнительные поля",
				"project": "МХП",
				"description": "",
				"source": "https://yt.innotech.com/issue/MHP-1595",
				"short_source": "https://yt.innotech.com/issue/MHP-1595",
				"priority": 3,
				"type": 4,
				"status_id": 4,
				"status_name": "Готово",
				"status_name_lat": "ready",
				"responsiblePM": 14,
				"responsiblePMName": "Матицин Андрій",
				"assignedTo": 6,
				"assignedToName": "Тесленко Олександр",
				"createdAt": "2025-08-13",
				"updatedAt": "2025-08-15",
				"planned_execution_date": "2025-08-13",
				"estimate": {
					"hours": 2,
					"minutes": 0
				}
			},
			{
				"id": 169,
				"title": "Киоск ковальская",
				"project": "ФЕМ Ковальская",
				"description": "Реализовать функцию поиска водителя по мобильному телефону и генерацию СМС",
				"source": "",
				"short_source": "",
				"priority": 3,
				"type": 4,
				"status_id": 4,
				"status_name": "Готово",
				"status_name_lat": "ready",
				"responsiblePM": 14,
				"responsiblePMName": "Матицин Андрій",
				"assignedTo": 6,
				"assignedToName": "Тесленко Олександр",
				"createdAt": "2025-09-16",
				"updatedAt": "2025-10-06",
				"planned_execution_date": "2025-09-16",
				"estimate": {
					"hours": 1,
					"minutes": 0
				}
			},
			{
				"id": 184,
				"title": "Укрпошта - зауваження по розподілу заявок",
				"project": "Укрпошта",
				"description": "",
				"source": "",
				"short_source": "",
				"priority": 3,
				"type": 1,
				"status_id": 4,
				"status_name": "Готово",
				"status_name_lat": "ready",
				"responsiblePM": 17,
				"responsiblePMName": "Цимбаліст Оля",
				"assignedTo": 6,
				"assignedToName": "Тесленко Олександр",
				"createdAt": "2025-09-19",
				"updatedAt": "2025-09-23",
				"planned_execution_date": "2025-09-19",
				"estimate": {
					"hours": 1,
					"minutes": 0
				}
			},
			{
				"id": 55,
				"title": "Вес тары",
				"project": "АПИ моб магистрал",
				"description": "",
				"source": "",
				"short_source": "",
				"priority": 5,
				"type": 3,
				"status_id": 5,
				"status_name": "Відхилено",
				"status_name_lat": "rejected",
				"responsiblePM": 14,
				"responsiblePMName": "Матицин Андрій",
				"assignedTo": 6,
				"assignedToName": "Тесленко Олександр",
				"createdAt": "2025-08-04",
				"updatedAt": "2025-08-04",
				"planned_execution_date": "",
				"estimate": {
					"hours": 1,
					"minutes": 0
				}
			},
			{
				"id": 58,
				"title": "Нова Пошта",
				"project": "Денка",
				"description": "",
				"source": "",
				"short_source": "",
				"priority": 5,
				"type": 3,
				"status_id": 5,
				"status_name": "Відхилено",
				"status_name_lat": "rejected",
				"responsiblePM": 14,
				"responsiblePMName": "Матицин Андрій",
				"assignedTo": 6,
				"assignedToName": "Тесленко Олександр",
				"createdAt": "2025-08-04",
				"updatedAt": "2025-08-04",
				"planned_execution_date": "",
				"estimate": {
					"hours": 1,
					"minutes": 0
				}
			},
			{
				"id": 60,
				"title": "Автоматизация",
				"project": "Юникс",
				"description": "Автоматизация запуска алгоритма планироания",
				"source": "https://task.track.com/project/iunik-treid/us/6",
				"short_source": "https://task.track.com/project/iunik-treid/us/6",
				"priority": 5,
				"type": 3,
				"status_id": 5,
				"status_name": "Відхилено",
				"status_name_lat": "rejected",
				"responsiblePM": 15,
				"responsiblePMName": "Холін Максим",
				"assignedTo": 6,
				"assignedToName": "Тесленко Олександр",
				"createdAt": "2025-08-04",
				"updatedAt": "2025-08-11",
				"planned_execution_date": "",
				"estimate": {
					"hours": 1,
					"minutes": 0
				}
			}
		],
		"statuses": {
			"all": 37,
			"active": "11",
			"line": "5",
			"work": "2",
			"review": "4",
			"ready": "22",
			"rejected": "3",
			"suspended": "1",
			"review_client": "0"
		}
	},
	9: {
		"tasks": [],
		"statuses": {
			"all": 0,
			"active": "0",
			"line": "0",
			"work": "0",
			"review": "0",
			"ready": "0",
			"rejected": "0",
			"suspended": "0",
			"review_client": "0"
		}
	},
	14: {
		"tasks": [],
		"statuses": {
			"all": 0,
			"active": "0",
			"line": "0",
			"work": "0",
			"review": "0",
			"ready": "0",
			"rejected": "0",
			"suspended": "0",
			"review_client": "0"
		}
	},
	16: {
		"tasks": [],
		"statuses": {
			"all": 0,
			"active": "0",
			"line": "0",
			"work": "0",
			"review": "0",
			"ready": "0",
			"rejected": "0",
			"suspended": "0",
			"review_client": "0"
		}
	},
	17: {
		"tasks": [],
		"statuses": {
			"all": 0,
			"active": "0",
			"line": "0",
			"work": "0",
			"review": "0",
			"ready": "0",
			"rejected": "0",
			"suspended": "0",
			"review_client": "0"
		}
	},
	18: {
		"tasks": [],
		"statuses": {
			"all": 0,
			"active": "0",
			"line": "0",
			"work": "0",
			"review": "0",
			"ready": "0",
			"rejected": "0",
			"suspended": "0",
			"review_client": "0"
		}
	},
	19: {
		"tasks": [],
		"statuses": {
			"all": 0,
			"active": "0",
			"line": "0",
			"work": "0",
			"review": "0",
			"ready": "0",
			"rejected": "0",
			"suspended": "0",
			"review_client": "0"
		}
	}
}

const dataPeople = [
	{
		id: 24,
		name: "Вікторія",
		surname: "Клименко",
		patronymic: "",
		fio: "Клименко В.",
		email: "",
		phone: "",
		position: "Developer",
		position_short: "DEV",
		sex: 2,
		state: "Працює",
		icon: "woman.png",
		deleted: 0
	},
	{
		id: 6,
		name: "Олександр",
		surname: "Тесленко",
		patronymic: "Юрійович",
		fio: "Тесленко О.Ю.",
		email: "alexandr.teslenko@gmail.com",
		phone: "+380958097565",
		position: "Developer",
		position_short: "DEV",
		sex: 1,
		state: "Працює",
		icon: "man.png",
		deleted: 0
	},
	{
		id: 9,
		name: "Віктор",
		surname: "Волков",
		patronymic: "",
		fio: "Волков В.",
		email: "volkov@mail.com",
		phone: "https://t.me/vv",
		position: "System administrator",
		position_short: "SA",
		sex: 1,
		state: "Працює",
		icon: "man_3.png",
		deleted: 0
	},
	{
		id: 14,
		name: "Андрій",
		surname: "Матицин",
		patronymic: "",
		fio: "Матицин А.",
		email: "matytsyn@mail.com",
		phone: "+380101000000",
		position: "Project manager",
		position_short: "PM",
		sex: 1,
		state: "Працює",
		icon: "technicalsupport_man.png",
		deleted: 0
	},
	{
		id: 18,
		name: "Вікторія",
		surname: "Пашкова",
		patronymic: "Вячеславівна",
		fio: "Пашкова В.В.",
		email: "victoriapash@mail.com",
		phone: "+380100030000",
		position: "Project manager",
		position_short: "PM",
		sex: 2,
		state: "Працює",
		icon: "technicalsupport_woman.png",
		deleted: 0
	},
	{
		id: 16,
		name: "Володимир",
		surname: "Камінський",
		patronymic: "",
		fio: "Камінський В.",
		email: "vladkaminsk@mail.com",
		phone: "+380200800000",
		position: "Supervisor",
		position_short: "SUP",
		sex: 1,
		state: "Працює",
		icon: "man_2.png",
		deleted: 0
	},
	{
		id: 19,
		name: "Аня",
		surname: "Костоправова",
		patronymic: "",
		fio: "Костоправова А.",
		email: "annakostopva@mail.com",
		phone: "+380000007110",
		position: "Tester",
		position_short: "QA",
		sex: 2,
		state: "Працює",
		icon: "woman_2.png",
		deleted: 0
	},
	{
		id: 17,
		name: "Оля",
		surname: "Цимбаліст",
		patronymic: "",
		fio: "Цимбаліст О.",
		email: "olgatsymbal@mail.com",
		phone: "+380110060000",
		position: "Project manager",
		position_short: "PM",
		sex: 2,
		state: "Звільнено",
		icon: "technicalsupport_woman.png",
		deleted: 1
	}
];
